import type { ChunkRecord, IndexStats, FolderNode, BrowseFile } from "./types";

export const MOCK_CHUNKS: ChunkRecord[] = [
  {
    chunk_id: "c001",
    file_path: "국가중점데이터/03.제안서/최종본/최종보고.pptx",
    project_path: "국가중점데이터",
    file_type: "pptx",
    doc_title: "최종보고",
    location: { slide: 12 },
    text: "국가중점데이터 구축 사업의 핵심 목표는 공공데이터의 품질 향상과 민간 활용 촉진입니다. NIA(한국지능정보사회진흥원)가 발주한 본 사업은 2025년 1월부터 12월까지 수행되며, 총 15개 분야의 데이터셋을 대상으로 합니다.",
    tags: ["발주처:NIA", "연도:2025", "산업:공공데이터"],
    mtime: "2026-02-15T09:30:00",
    hash: "a1b2c3d4",
  },
  {
    chunk_id: "c002",
    file_path: "국가중점데이터/03.제안서/최종본/최종보고.pptx",
    project_path: "국가중점데이터",
    file_type: "pptx",
    doc_title: "최종보고",
    location: { slide: 15 },
    text: "데이터 품질관리 체계 구축 방안: 1) 품질진단 자동화 도구 도입 2) 메타데이터 표준화 3) 품질지표 모니터링 대시보드 구축. 특히 교통데이터와 환경데이터 분야에서 실시간 품질 검증 파이프라인을 구성합니다.",
    tags: ["발주처:NIA", "연도:2025", "키워드:품질관리"],
    mtime: "2026-02-15T09:30:00",
    hash: "a1b2c3d5",
  },
  {
    chunk_id: "c003",
    file_path: "국가중점데이터/04.수행/현황분석/기관현황조사.pdf",
    project_path: "국가중점데이터",
    file_type: "pdf",
    doc_title: "기관현황조사",
    location: { page: 23 },
    text: "한국교통안전공단(TS)의 교통사고 데이터는 연간 약 200만 건이 수집되며, 현재 CSV 형태로 내부 시스템에 저장됩니다. 데이터 개방 시 개인정보 비식별화 처리가 필수적이며, 기존 시스템과의 연동 API 개발이 필요합니다.",
    tags: ["기관:한국교통안전공단", "연도:2025", "데이터:교통사고"],
    mtime: "2026-01-20T14:00:00",
    hash: "b2c3d4e5",
  },
  {
    chunk_id: "c004",
    file_path: "국가중점데이터/04.수행/현황분석/기관현황조사.pdf",
    project_path: "국가중점데이터",
    file_type: "pdf",
    doc_title: "기관현황조사",
    location: { page: 45 },
    text: "환경부 산하 한국환경공단의 대기질 모니터링 데이터는 전국 650개 측정소에서 실시간 수집됩니다. 현재 시스템은 Oracle DB 기반이며, 개방형 API(REST)를 통해 시간별 데이터 제공 중입니다. PM2.5, PM10, O3, NO2 등 주요 항목을 포함합니다.",
    tags: ["기관:한국환경공단", "연도:2025", "데이터:대기질"],
    mtime: "2026-01-20T14:00:00",
    hash: "b2c3d4e6",
  },
  {
    chunk_id: "c005",
    file_path: "국가중점데이터/05.분석/데이터현황.xlsx",
    project_path: "국가중점데이터",
    file_type: "xlsx",
    doc_title: "데이터현황",
    location: { sheet: "기관별현황", row: 5 },
    text: "한국지능정보사회진흥원 | 공공데이터포털 | 데이터셋 32,000건 | API 호출 월 500만건 | 정형(CSV/JSON) | 품질등급 A",
    tags: ["기관:NIA", "시스템:공공데이터포털"],
    mtime: "2026-02-01T11:00:00",
    hash: "c3d4e5f6",
  },
  {
    chunk_id: "c006",
    file_path: "국가중점데이터/05.분석/데이터현황.xlsx",
    project_path: "국가중점데이터",
    file_type: "xlsx",
    doc_title: "데이터현황",
    location: { sheet: "시스템현황", row: 12 },
    text: "교통정보시스템(UTIS) | 국토교통부 | 실시간 교통속도/소통정보 | PostgreSQL | 일 200GB | REST API 제공 | 2024년 고도화 완료",
    tags: ["시스템:UTIS", "기관:국토교통부"],
    mtime: "2026-02-01T11:00:00",
    hash: "c3d4e5f7",
  },
  {
    chunk_id: "c007",
    file_path: "디지털플랫폼정부/02.제안서/DPG_제안서_v3.pptx",
    project_path: "디지털플랫폼정부",
    file_type: "pptx",
    doc_title: "DPG_제안서_v3",
    location: { slide: 8 },
    text: "디지털플랫폼정부 구현을 위한 핵심 아키텍처: 마이크로서비스 기반 공통 플랫폼, API Gateway를 통한 서비스 통합, 클라우드 네이티브 인프라(K8s), 제로트러스트 보안 모델 적용. 행정안전부 주관으로 2025-2027 3개년 추진.",
    tags: ["발주처:행정안전부", "연도:2025", "키워드:마이크로서비스"],
    mtime: "2026-02-10T16:00:00",
    hash: "d4e5f6g7",
  },
  {
    chunk_id: "c008",
    file_path: "디지털플랫폼정부/04.수행/EA분석/EA_현행아키텍처.pdf",
    project_path: "디지털플랫폼정부",
    file_type: "pdf",
    doc_title: "EA_현행아키텍처",
    location: { page: 7 },
    text: "현행 전자정부 프레임워크(eGovFrame) 기반 시스템 326개 중 78%가 모놀리식 아키텍처로 운영 중이며, 평균 운영 연한은 8.2년입니다. 클라우드 전환율은 23%에 불과하며, API 표준화율은 45%입니다.",
    tags: ["키워드:eGovFrame", "키워드:클라우드전환"],
    mtime: "2026-01-15T10:00:00",
    hash: "e5f6g7h8",
  },
  {
    chunk_id: "c009",
    file_path: "AI분석플랫폼/03.제안서/AI플랫폼_제안서.pptx",
    project_path: "AI분석플랫폼",
    file_type: "pptx",
    doc_title: "AI플랫폼_제안서",
    location: { slide: 22 },
    text: "MLOps 파이프라인 구축 방안: Kubeflow 기반 모델 학습/배포 자동화, Feature Store(Feast) 도입, 모델 버전 관리(MLflow), A/B 테스트 프레임워크. GPU 클러스터(A100 x 8) 기반 분산 학습 환경 구성.",
    tags: ["키워드:MLOps", "키워드:Kubeflow", "산업:AI"],
    mtime: "2026-02-18T13:00:00",
    hash: "f6g7h8i9",
  },
  {
    chunk_id: "c010",
    file_path: "AI분석플랫폼/05.분석/모델성능비교.csv",
    project_path: "AI분석플랫폼",
    file_type: "csv",
    doc_title: "모델성능비교",
    location: { row: 3 },
    text: "GPT-4o | 텍스트분류 | Accuracy: 0.94 | F1: 0.92 | Latency: 320ms | 비용: $0.005/req | 2025-12 평가",
    tags: ["키워드:GPT-4o", "산업:AI"],
    mtime: "2026-02-12T09:00:00",
    hash: "g7h8i9j0",
  },
  {
    chunk_id: "c011",
    file_path: "AI분석플랫폼/06.개발/데이터전처리.ipynb",
    project_path: "AI분석플랫폼",
    file_type: "ipynb",
    doc_title: "데이터전처리",
    location: { cell: 5 },
    text: "# 텍스트 전처리 파이프라인\nimport pandas as pd\nfrom konlpy.tag import Okt\n\ndef preprocess_text(text):\n    okt = Okt()\n    tokens = okt.morphs(text, stem=True)\n    return ' '.join([t for t in tokens if len(t) > 1])",
    tags: ["키워드:전처리", "키워드:KoNLPy"],
    mtime: "2026-02-19T17:00:00",
    hash: "h8i9j0k1",
  },
  {
    chunk_id: "c012",
    file_path: "스마트시티/03.제안서/스마트시티_ISP_최종.pptx",
    project_path: "스마트시티",
    file_type: "pptx",
    doc_title: "스마트시티_ISP_최종",
    location: { slide: 35 },
    text: "스마트시티 통합플랫폼 아키텍처: IoT 센서 데이터 수집(MQTT) → 실시간 스트리밍(Kafka) → 데이터레이크(MinIO) → 분석엔진(Spark) → 시각화(Grafana). 세종시/부산시 시범 적용 후 전국 확대.",
    tags: ["발주처:국토교통부", "키워드:IoT", "산업:스마트시티"],
    mtime: "2026-02-05T08:00:00",
    hash: "i9j0k1l2",
  },
];

export const MOCK_FOLDER_TREE: FolderNode = {
  name: "컨설팅산출물",
  path: "",
  file_count: 0,
  children: [
    {
      name: "국가중점데이터",
      path: "국가중점데이터",
      file_count: 0,
      children: [
        { name: "01.RFP", path: "국가중점데이터/01.RFP", file_count: 2, children: [] },
        { name: "02.사전조사", path: "국가중점데이터/02.사전조사", file_count: 3, children: [] },
        {
          name: "03.제안서",
          path: "국가중점데이터/03.제안서",
          file_count: 0,
          children: [
            { name: "최종본", path: "국가중점데이터/03.제안서/최종본", file_count: 1, children: [] },
            { name: "초안", path: "국가중점데이터/03.제안서/초안", file_count: 3, children: [] },
          ],
        },
        {
          name: "04.수행",
          path: "국가중점데이터/04.수행",
          file_count: 0,
          children: [
            { name: "현황분석", path: "국가중점데이터/04.수행/현황분석", file_count: 2, children: [] },
            { name: "설계", path: "국가중점데이터/04.수행/설계", file_count: 4, children: [] },
          ],
        },
        { name: "05.분석", path: "국가중점데이터/05.분석", file_count: 3, children: [] },
      ],
    },
    {
      name: "디지털플랫폼정부",
      path: "디지털플랫폼정부",
      file_count: 0,
      children: [
        { name: "02.제안서", path: "디지털플랫폼정부/02.제안서", file_count: 2, children: [] },
        {
          name: "04.수행",
          path: "디지털플랫폼정부/04.수행",
          file_count: 0,
          children: [
            { name: "EA분석", path: "디지털플랫폼정부/04.수행/EA분석", file_count: 3, children: [] },
          ],
        },
      ],
    },
    {
      name: "AI분석플랫폼",
      path: "AI분석플랫폼",
      file_count: 0,
      children: [
        { name: "03.제안서", path: "AI분석플랫폼/03.제안서", file_count: 1, children: [] },
        { name: "05.분석", path: "AI분석플랫폼/05.분석", file_count: 2, children: [] },
        { name: "06.개발", path: "AI분석플랫폼/06.개발", file_count: 4, children: [] },
      ],
    },
    {
      name: "스마트시티",
      path: "스마트시티",
      file_count: 0,
      children: [
        { name: "03.제안서", path: "스마트시티/03.제안서", file_count: 1, children: [] },
      ],
    },
  ],
};

export const MOCK_BROWSE_FILES: BrowseFile[] = [
  { file_path: "국가중점데이터/03.제안서/최종본/최종보고.pptx", file_type: "pptx", doc_title: "최종보고", chunk_count: 42, mtime: "2026-02-15T09:30:00", project_path: "국가중점데이터" },
  { file_path: "국가중점데이터/04.수행/현황분석/기관현황조사.pdf", file_type: "pdf", doc_title: "기관현황조사", chunk_count: 68, mtime: "2026-01-20T14:00:00", project_path: "국가중점데이터" },
  { file_path: "국가중점데이터/05.분석/데이터현황.xlsx", file_type: "xlsx", doc_title: "데이터현황", chunk_count: 15, mtime: "2026-02-01T11:00:00", project_path: "국가중점데이터" },
  { file_path: "디지털플랫폼정부/02.제안서/DPG_제안서_v3.pptx", file_type: "pptx", doc_title: "DPG_제안서_v3", chunk_count: 35, mtime: "2026-02-10T16:00:00", project_path: "디지털플랫폼정부" },
  { file_path: "디지털플랫폼정부/04.수행/EA분석/EA_현행아키텍처.pdf", file_type: "pdf", doc_title: "EA_현행아키텍처", chunk_count: 28, mtime: "2026-01-15T10:00:00", project_path: "디지털플랫폼정부" },
  { file_path: "AI분석플랫폼/03.제안서/AI플랫폼_제안서.pptx", file_type: "pptx", doc_title: "AI플랫폼_제안서", chunk_count: 30, mtime: "2026-02-18T13:00:00", project_path: "AI분석플랫폼" },
  { file_path: "AI분석플랫폼/05.분석/모델성능비교.csv", file_type: "csv", doc_title: "모델성능비교", chunk_count: 8, mtime: "2026-02-12T09:00:00", project_path: "AI분석플랫폼" },
  { file_path: "AI분석플랫폼/06.개발/데이터전처리.ipynb", file_type: "ipynb", doc_title: "데이터전처리", chunk_count: 12, mtime: "2026-02-19T17:00:00", project_path: "AI분석플랫폼" },
  { file_path: "스마트시티/03.제안서/스마트시티_ISP_최종.pptx", file_type: "pptx", doc_title: "스마트시티_ISP_최종", chunk_count: 45, mtime: "2026-02-05T08:00:00", project_path: "스마트시티" },
];

export const MOCK_STATS: IndexStats = {
  total_files: 47,
  total_chunks: 1284,
  last_updated: "2026-02-21T11:12:52",
  by_type: {
    pptx: 18,
    pdf: 12,
    xlsx: 8,
    csv: 4,
    ipynb: 3,
    hwp: 1,
    docx: 1,
  },
  by_project: [
    { project_path: "국가중점데이터", file_count: 3, chunk_count: 11 },
    { project_path: "AI분석플랫폼", file_count: 4, chunk_count: 6 },
    { project_path: "공공데이터활용실태조사", file_count: 2, chunk_count: 5 },
    { project_path: "디지털플랫폼정부", file_count: 2, chunk_count: 4 },
    { project_path: "공공기관EA수립", file_count: 1, chunk_count: 2 },
  ],
  failed_files: [
    { file_path: "국가중점데이터/04.수행/설계/시스템구성도_v2.pptx", error: "파일 손상: 슬라이드 읽기 실패", last_attempt: "2026-02-21T08:10:00" },
    { file_path: "스마트시티/05.보고서/최종보고_스캔본.pdf", error: "텍스트 추출 불가 (스캔 이미지 PDF)", last_attempt: "2026-02-21T08:12:00" },
  ],
};
